name: flutter_helpers
version: 0.0.1

environment:
  sdk: '>=3.12.2 <4.0.0'
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true