name: flutter_helpers
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true