import 'dart:math' as math;

import 'package:flutter_helpers/flutter_helpers.dart';
import 'package:material_ui/material_ui.dart';

part 'package:flutter_helpers/dart/extensions/int_to_duration_extension.dart';
part 'package:flutter_helpers/dart/extensions/iterable_extensions/date_time_iterable_extension.dart';
part 'package:flutter_helpers/dart/extensions/iterable_extensions/nullable_iterable_extension.dart';
part 'package:flutter_helpers/dart/extensions/iterable_extensions/numeric_iterable_extension.dart';
part 'package:flutter_helpers/dart/extensions/map_extensions/nullable_map_extension.dart';
part 'package:flutter_helpers/dart/extensions/num_extension.dart';
part 'package:flutter_helpers/dart/extensions/string_extensions/nullable_string_extension.dart';
part 'package:flutter_helpers/flutter/helpers/state_helper.dart';
part 'package:flutter_helpers/flutter/models/center_text_configuration.dart';
part 'package:flutter_helpers/flutter/models/check_box_button_configuration.dart';
part 'package:flutter_helpers/flutter/models/radio_button_configuration.dart';
part 'package:flutter_helpers/flutter/models/snack_bar_configuration.dart';
part 'package:flutter_helpers/flutter/models/tap_detector_configuration.dart';
part 'package:flutter_helpers/flutter/models/text_form_field_dialog_configuration.dart';
part 'package:flutter_helpers/flutter/models/text_style_builder.dart';
part 'package:flutter_helpers/flutter/models/yes_no_dialog_configuration.dart';
part 'package:flutter_helpers/flutter/widget_configuration.dart';
part 'package:flutter_helpers/flutter/widgets/check_box_button.dart';
part 'package:flutter_helpers/flutter/widgets/dialog_button.dart';
part 'package:flutter_helpers/flutter/widgets/dialogs/snack_bar.dart';
part 'package:flutter_helpers/flutter/widgets/dialogs/text_dialog.dart';
part 'package:flutter_helpers/flutter/widgets/dialogs/text_form_field_dialog.dart';
part 'package:flutter_helpers/flutter/widgets/dialogs/yes_no_dialog.dart';
part 'package:flutter_helpers/flutter/widgets/hidden_widget.dart';
part 'package:flutter_helpers/flutter/widgets/page_container.dart';
part 'package:flutter_helpers/flutter/widgets/radio_button.dart';
